
Run msbuild SilentXMRMiner.sln /p:Configuration=Release /p:Platform="Any CPU"
MSBuild version 17.14.14+a129329f1 for .NET Framework
Build started 7/15/2025 6:03:05 PM.

Project "D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner.sln" (1) is building "D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner\Silent XMR Miner Builder.vbproj" (2) on node 1 (default targets).
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1259,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner\Silent XMR Miner Builder.vbproj]
_CleanRecordFileWrites:
  Creating directory "obj\Release\".
Done Building Project "D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner\Silent XMR Miner Builder.vbproj" (default targets) -- FAILED.
Done Building Project "D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner.sln" (default targets) -- FAILED.

Build FAILED.

"D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner.sln" (default target) (1) ->
"D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner\Silent XMR Miner Builder.vbproj" (default target) (2) ->
(GetReferenceAssemblyPaths target) -> 
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1259,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [D:\a\SilentXMRMiner\SilentXMRMiner\SilentXMRMiner\Silent XMR Miner Builder.vbproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.14
Error: Process completed with exit code 1.
