# This workflow builds the SilentXMRMiner project using .NET on Windows.
# It will run automatically when changes are pushed to the 'master' branch
# or when a pull request is opened against the 'master' branch.

name: Build SilentXMRMiner

on:
  push:
    branches:
      - master # Change this to 'main' if your default branch is named 'main'
  pull_request:
    branches:
      - master # Change this to 'main' if your default branch is named 'main'

jobs:
  build:
    # Use a Windows environment, as .NET projects are typically built on Windows.
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      # Clones the repository to the runner.
      uses: actions/checkout@v4

    - name: Install .NET Framework 4.5 Developer Pack
      # Explicitly downloads and installs the .NET Framework 4.5 Developer Pack.
      # This ensures that the necessary reference assemblies for v4.5 are present.
      # The installer is run silently using '/q' and '/norestart' flags.
      shell: powershell
      run: |
        $url = "https://download.microsoft.com/download/B/A/4/BA4A7E71-2906-4B2D-A0E6-764E68764096/NDP45SDK-KB2750041-x86-x64-AllOS.exe"
        $output = "$env:TEMP\NDP45SDK.exe"
        Write-Host "Downloading .NET Framework 4.5 Developer Pack from $url..."
        Invoke-WebRequest -Uri $url -OutFile $output
        Write-Host "Installing .NET Framework 4.5 Developer Pack..."
        Start-Process -FilePath $output -ArgumentList "/q /norestart" -Wait -PassThru | Out-Null
        Write-Host ".NET Framework 4.5 Developer Pack installation complete."

    - name: Setup MSBuild
      # Installs the necessary MSBuild tools. This action is still useful for setting up the environment.
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet Packages
      # Restores all NuGet packages required by the solution using MSBuild's restore target.
      # This is the correct way to restore packages for .NET Framework projects.
      run: msbuild SilentXMRMiner.sln /t:Restore

    - name: Build Project
      # Builds the project in Release configuration using MSBuild.
      # The /p:Configuration=Release flag sets the build configuration.
      # The /p:Platform="Any CPU" is often needed for .NET Framework projects.
      run: msbuild SilentXMRMiner.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Publish Build Artifacts
      # Optional: Uploads the compiled executable as a workflow artifact.
      # This makes the build output easily downloadable from the GitHub Actions run summary.
      # Adjust the 'path' to match where your compiled .exe is located after building.
      # Common paths are 'SilentXMRMiner/bin/Release/net8.0/' or similar, depending on your project structure and target framework.
      uses: actions/upload-artifact@v4
      with:
        name: SilentXMRMiner-Executable
        path: SilentXMRMiner/bin/Release/net45/ # Adjusted path to reflect .NET Framework 4.5 output
        # If your project is a single .exe, you might specify: path: SilentXMRMiner/bin/Release/net45/SilentXMRMiner.exe
        # Or if it's a self-contained deployment: path: SilentXMRMiner/bin/Release/net45/publish/
